spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_smart_home
    username: postgres
    password: admin
  jpa:
    hibernate.dll-auto: none
    open-in-view: false
  sql.init.mode: always
server:
  port: 0
