spring:
  application:
    name: gateway
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/payment/**
        - id: delivery
          uri: lb://delivery
          predicates:
            - Path=/delivery/**



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10
server:
  port: 8080