grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

hibernate:
  show-sql: true
  jdbc:
    time-zone: UTC

topics:
  snapshots: telemetry.snapshots.v1
  hubs: telemetry.hubs.v1

kafka:
  bootstrap-server: localhost:9092
  key-deserializer-class: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer-classes:
    snapshots: ru.yandex.practicum.serialization.SensorsSnapshotDeserializer
    hub-events: ru.yandex.practicum.serialization.HubEventsDeserializer